#!/usr/bin/env bash
# Install Haproxy and configure two servers to be load-balanced

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update
sudo apt-get install -y haproxy

echo "ENABLED=1" > /etc/default/haproxy

echo "
listen load_balancer
   bind 0.0.0.0:80
   mode http
   stats enable
   stats uri /haproxy?stats
   balance roundrobin
   option httpclose
   option forwardfor
   server 17682-web-01 3.236.147.89:80 check
   server 17682-web-02 18.232.73.156:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start

# !/usr/bin/env bash
# Configure Nginx so that its HTTP response contains
# a custom header
# Add HAProxy PPA
#sudo apt-get -y install software-properties-common
#sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
#sudo apt-get -y update

# Install HAProxy and configure it
#sudo apt-get -y install haproxy
#sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
#sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 17682-web-01 3.236.147.89:80 check\n\tserver 17682-web-02 18.232.73.156:80 check\n' /etc/haproxy/haproxy.cfg
#sudo sed -i -e '$afrontend haproxy-main\n\tbind *:80\n\toption forwardfor\n\tdefault_backend apache_webservers\n\nbackend nginx webservers\n\tbalance roundrobin\n\tserver 39187-web-01	100.25.163.234:80 check\n\tserver 39187-web-02	35.175.104.221:80 check\n' /etc/haproxy/haproxy.cfg
#sudo service haproxy restart
