#!/usr/bin/env bash
# Install Haproxy and configure two servers to be load-balanced

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update
sudo apt-get install -y haproxy


sudo sed -i -e '$afrontend haproxy-main\n\tbind *:80\n\toption forwardfor\n\tdefault_backend webservers\n\nbackend webservers\n\tbalance roundrobin\n\tserver 39187-web-01	100.25.163.234:80 check\n\tserver 39187-web-02	35.175.104.221:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy start
